export const products = [
  {
    id: 1,
    image: { src: '/images/image-1.jpeg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 799,
    category: 'man',
  },
  {
    id: 2,
    image: { src: '/images/image-2.jpg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 1120,
    category: 'man',
  },
  {
    id: 3,
    image: { src: '/images/image-3.jpg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 1020,
    category: 'man',
  },
  {
    id: 4,
    image: { src: '/images/image-1.jpeg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 5,
    image: { src: '/images/image-2.jpg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 6,
    image: { src: '/images/image-3.jpg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 7,
    image: { src: '/images/image-1.jpeg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 8,
    image: { src: '/images/image-2.jpg', alt: 'man-1' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 9,
    image: { src: '/images/image-3.jpg', alt: 'man-2' },
    name: "Man's Fashion",
    price: 120,
    category: 'man',
  },
  {
    id: 10,
    image: { src: '/images/image-1.jpeg', alt: 'man-3' },
    name: '',
    price: 120,
    category: 'man',
  },
  {
    id: 11,
    image: { src: '/images/image-11.webp', alt: 'woman-1' },
    name: 'Women Fashion',
    price: 120,
    category: 'women',
  },
  {
    id: 12,
    image: { src: '/images/image-12.webp', alt: 'woman-2' },
    name: 'Women Fashion',
    price: 120,
    category: 'women',
  },
  {
    id: 13,
    image: { src: '/images/image-13.webp', alt: 'woman-3' },
    name: 'Women Fashion',
    price: 120,
    category: 'women',
  },
  {
    id: 14,
    image: { src: '/images/image-11.webp', alt: 'woman-1' },
    name: 'Women Fashion',
    price: 120,
    category: 'women',
  },
  {
    id: 15,
    image: { src: '/images/image-21.jpg', alt: 'kid-1' },
    name: "Kids' Fashion",
    price: 120,
    category: 'kids',
  },
  {
    id: 16,
    image: { src: '/images/image-22.jpg', alt: 'kid-2' },
    name: "Kids' Fashion",
    price: 120,
    category: 'kids',
  },
  {
    id: 17,
    image: { src: '/images/image-23.webp', alt: 'kid-3' },
    name: "Kids' Fashion",
    price: 120,
    category: 'kids',
  },
  {
    id: 18,
    image: { src: '/images/image-21.jpg', alt: 'kid-3' },
    name: "Kids' Fashion",
    price: 120,
    category: 'kids',
  },
];
